// Optional real-browser test; served assets are explicitly whitelisted, not this file.
const assert = require('node:assert/strict');
const path = require('node:path');
const {chromium} = require(process.env.ROLLOUT_REVIEW_PLAYWRIGHT);

(async () => {
  const browser = await chromium.launch({headless: true, args: ['--no-sandbox']});
  try {
    const page = await browser.newPage({viewport: {width: 1440, height: 1050}});
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('dialog', dialog => dialog.accept());
    const url = process.argv[2];
    await page.goto(url);
    await page.waitForFunction(() => document.getElementById('catalogStatus').textContent.includes('更新'));
    assert.equal(await page.locator('#versionFilter').inputValue(), 'v3');
    assert.equal(await page.locator('#runs .run').count(), 0);
    assert(await page.locator('#detail').evaluate(el => el.hidden));
    assert.equal(await page.locator('#video').getAttribute('src'), null);
    await page.selectOption('#versionFilter', 'v2');
    await page.waitForFunction(() => document.getElementById('video').readyState >= 2);
    assert.equal(await page.locator('#runTitle').textContent(), 'build_tower');
    assert.equal(await page.locator('#video').evaluate(v => v.controls), false);
    assert.equal(await page.locator('#video').getAttribute('controls'), null);
    await page.locator('#video').click();
    assert(await page.locator('#video').evaluate(v => v.paused));
    await page.selectOption('#speed', '2');
    assert.equal(await page.locator('#video').evaluate(v => v.playbackRate), 2);
    await page.locator('#seekSeconds').fill('0.5');
    await page.locator('#seekTime').click();
    await page.waitForFunction(() => Math.abs(document.getElementById('video').currentTime - 0.5) < 0.01);
    const before = await page.locator('#video').evaluate(v => Math.floor(v.currentTime * 25));
    await page.locator('#nextFrame').click();
    assert.equal(await page.locator('#video').evaluate(v => Math.floor(v.currentTime * 25)), before + 1);
    await page.locator('#timeline').focus();
    await page.keyboard.press('Period');
    assert.equal(await page.locator('#video').evaluate(v => Math.floor(v.currentTime * 25)), before + 2);
    await page.keyboard.press('Comma');
    assert.equal(await page.locator('#video').evaluate(v => Math.floor(v.currentTime * 25)), before + 1);
    assert(await page.locator('#video').evaluate(v => v.paused));
    await page.locator('#clipComment').focus();
    await page.keyboard.press('Period');
    assert.equal(await page.locator('#clipComment').inputValue(), '.');
    assert.equal(await page.locator('#video').evaluate(v => Math.floor(v.currentTime * 25)), before + 1);
    await page.locator('#clipComment').fill('');
    await page.locator('#play').click();
    await page.waitForFunction(() => document.getElementById('video').currentTime > 0.8);
    await page.locator('#play').click();
    await page.locator('#timeline').scrollIntoViewIfNeeded();
    const box = await page.locator('#timeline').boundingBox();
    // Reverse selection follows the moving (left) edge, not the sorted end.
    await page.mouse.move(box.x + box.width * 0.8, box.y + box.height / 2);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width * 0.4, box.y + box.height / 2, {steps: 8});
    await page.waitForFunction(() => {const v=document.getElementById('video');return !v.seeking && Math.abs(v.currentTime/v.duration-0.4)<0.01;});
    assert(Math.abs(Number(await page.locator('#clipStart').inputValue())/4.04-0.4)<0.01);
    assert(Math.abs(Number(await page.locator('#clipEnd').inputValue())/4.04-0.8)<0.01);
    await page.mouse.up();
    assert(await page.locator('#video').evaluate(v => v.paused));
    await page.mouse.move(box.x + box.width * 0.25, box.y + box.height / 2);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width * 0.45, box.y + box.height / 2, {steps: 8});
    // Assert during pointer-down, not only on release.
    await page.waitForFunction(() => {const v=document.getElementById('video');return !v.seeking && Math.abs(v.currentTime/v.duration-0.45)<0.01;});
    await page.mouse.move(box.x + box.width * 0.6, box.y + box.height / 2, {steps: 8});
    await page.mouse.up();
    await page.waitForFunction(() => {const v=document.getElementById('video');return !v.seeking && Math.abs(v.currentTime/v.duration-0.6)<0.01;});
    assert(await page.locator('#video').evaluate(v => v.paused));
    assert(Number(await page.locator('#clipEnd').inputValue()) > Number(await page.locator('#clipStart').inputValue()));
    await page.locator('#clipComment').fill('Behavior segment one <script>not executed</script>');
    await page.locator('#clipTags').fill('恢复, 规划');
    await page.locator('#addClip').click();
    assert.equal(await page.locator('.clip-item').count(), 1);
    await page.locator('#clipStart').fill('0.4');
    await page.locator('#clipEnd').fill('0.8');
    await page.locator('#loop').check();
    await page.locator('#previewClip').click();
    await page.waitForTimeout(800);
    const loopTime = await page.locator('#video').evaluate(v => v.currentTime);
    assert(loopTime >= 0.35 && loopTime <= 0.95, `Loop escaped selection: ${loopTime}`);
    await page.locator('#video').evaluate(v => v.pause());
    await page.locator('#loop').uncheck();
    await page.locator('#clipComment').fill('Short loop segment');
    await page.locator('#addClip').click();
    await page.locator('#comment').fill('Overall behavior comment');
    await page.locator('#selected').check();
    await page.locator('#reviewed').check();
    await page.locator('#save').click();
    await page.waitForFunction(() => document.getElementById('saveState').textContent.includes('r1'));
    await page.reload();
    await page.waitForFunction(() => document.getElementById('video').readyState >= 2);
    assert.equal(await page.locator('.clip-item').count(), 2);
    assert.equal(await page.locator('#comment').inputValue(), 'Overall behavior comment');
    assert.equal(await page.locator('#speed').inputValue(), '2');
    assert(await page.locator('#selected').isChecked());
    await page.locator('.clip-item').first().getByRole('button', {name: '编辑', exact: true}).click();
    await page.locator('#clipComment').fill('Edited behavior segment');
    await page.locator('#addClip').click();
    await page.locator('#save').click();
    await page.waitForFunction(() => document.getElementById('saveState').textContent.includes('r2'));
    await page.locator('#history').click();
    await page.locator('#historyDialog').waitFor({state: 'visible'});
    assert((await page.locator('#historyContent').textContent()).includes('Behavior segment one'));
    await page.locator('#closeHistory').click();
    const exported = await page.request.get(url + 'api/export?format=json&selected=1');
    const json = await exported.json();
    assert.equal(json.rows.length, 1);
    assert.equal(json.rows[0].annotation.clips.length, 2);
    assert.equal(json.rows[0].annotation.clips[0].comment, 'Edited behavior segment');
    assert.equal(typeof json.rows[0].annotation.clips[0].start_step, 'number');
    await page.locator('#comment').fill('Unsaved draft survives reload');
    await page.reload();
    await page.waitForFunction(() => document.getElementById('comment').value === 'Unsaved draft survives reload');
    await page.locator('#save').click();
    await page.waitForFunction(() => document.getElementById('saveState').textContent.includes('r3'));
    await page.selectOption('#versionFilter', 'v3');
    assert(await page.locator('#detail').evaluate(el => el.hidden));
    assert.equal(await page.locator('#video').getAttribute('src'), null);
    await page.reload();
    await page.waitForFunction(() => document.getElementById('catalogStatus').textContent.includes('更新'));
    assert.equal(await page.locator('#versionFilter').inputValue(), 'v3');
    assert.equal(await page.locator('#runs .run').count(), 0);
    const filtered = await (await page.request.get(url+'api/export?format=json&selected=1&version=v3')).json();
    assert.equal(filtered.rows.length, 0);
    await page.selectOption('#versionFilter', 'v2');
    await page.waitForFunction(() => document.getElementById('video').readyState >= 2);
    assert.equal(await page.locator('.clip-item').count(), 2);
    assert.equal(await page.locator('#comment').inputValue(), 'Unsaved draft survives reload');
    await page.locator('#viewer').scrollIntoViewIfNeeded();
    await page.screenshot({path: path.join(process.env.ROLLOUT_REVIEW_SCREENSHOTS, 'desktop.png'), fullPage: true});
    await page.setViewportSize({width: 650, height: 900});
    await page.screenshot({path: path.join(process.env.ROLLOUT_REVIEW_SCREENSHOTS, 'mobile.png'), fullPage: true});
    assert.deepEqual(errors, []);
    console.log(JSON.stringify({browser: 'chromium', passed: ['v3_default_no_old_video', 'version_persistence', 'version_export', 'old_clips_retained', 'video_decode', 'custom_controls_only', 'speed_2x', 'seek', 'frame_step', 'frame_shortcuts', 'input_shortcut_guard', 'play_pause', 'forward_reverse_scrub_during_drag', 'release_holds_frame', 'drag_selection', 'segment_loop', 'two_clips', 'save_reload', 'edit_revision', 'history', 'selected_export', 'draft_restore', 'no_script_errors']}));
  } finally {await browser.close();}
})().catch(error => {console.error(error); process.exitCode = 1;});
