// Offline Chromium check. No credentials, remote websites, or model calls.
const { chromium } = require(process.env.REPORT_PLAYWRIGHT || '/tmp/rollout-review-browser.HpuzaB/node_modules/playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { pathToFileURL } = require('node:url');
const root = path.resolve(process.argv[2]);
(async () => {
  const browser = await chromium.launch({headless:true, args:['--no-sandbox']});
  const page = await browser.newPage({viewport:{width:1440,height:1050}});
  const errors=[];
  page.on('pageerror', e=>errors.push(e.message));
  await page.goto(pathToFileURL(path.join(root,'index.html')).href);
  await page.waitForSelector('.rr-report', {timeout:20000});
  await page.evaluate(()=>document.fonts.ready);
  await page.locator('.rr-metrics').scrollIntoViewIfNeeded();
  await page.waitForSelector('.recharts-bar-rectangle', {timeout:15000});
  const painted = await page.locator('.recharts-bar-rectangle').evaluateAll(nodes=>nodes.filter(n=>n.getBoundingClientRect().width>0).length);
  assert(painted>=12,`Expected 12 painted bars, got ${painted}`);
  await page.screenshot({path:path.join(root,'report-desktop.png')});
  await page.locator('[data-component-id="panel-score-ranking"]').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(root,'report-chart.png')});
  await page.getByRole('button',{name:'成功率',exact:true}).click();
  await page.waitForSelector('.recharts-bar-rectangle');
  await page.getByRole('button',{name:'平均 Score',exact:true}).click();
  assert.equal(await page.locator('#results .rr-table tbody tr').count(),10);
  await page.locator('#method').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(root,'report-method.png')});
  await page.getByText('10 个任务：初态与期望终态',{exact:true}).click();
  assert.equal(await page.locator('.rr-task').count(),10);
  await page.locator('#findings').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(root,'report-findings.png')});
  assert.equal(await page.locator('.rr-clip').count(),12);
  const firstClip=page.locator('.rr-clip').first();
  await firstClip.getByRole('button',{name:'播放',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.rr-clip video').currentTime>0.1);
  await firstClip.getByRole('button',{name:'暂停',exact:true}).click();
  await firstClip.locator('select').selectOption('4');
  assert.equal(await firstClip.locator('video').evaluate(v=>v.playbackRate),4);
  const refLink=page.locator('a[href="https://github.com/zjwzcx/Awesome-Astra-Embodied-AI"]').first();
  await refLink.hover();
  await page.getByText('用户推荐的社区索引，区分仿真控制、真机控制、调用预训练策略、Real-to-sim 和环境/RL 构建。作为发现原始案例的入口，不把不同演示的结果混成统一基准。',{exact:true}).waitFor({state:'visible'});
  await page.screenshot({path:path.join(root,'reference-hover.png')});
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:path.join(root,'report-mobile.png')});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Report overflows mobile viewport');
  await page.goto(pathToFileURL(path.join(root,'gallery.html')).href);
  await page.waitForSelector('.card');
  assert.equal(await page.locator('.card').count(),100);
  await page.locator('#method').selectOption('gpt');
  assert.equal(await page.locator('.card').count(),50);
  await page.locator('#status').selectOption('idle');
  assert.equal(await page.locator('.card').count(),2);
  await page.locator('#clear').click();
  await page.locator('#task').selectOption('build_tower');
  assert.equal(await page.locator('.card').count(),10);
  await page.locator('#search').fill('not-a-real-task-xyz');
  assert.equal(await page.locator('.card').count(),0);
  await page.locator('#clear').click();
  await page.locator('#scope').selectOption('clips');
  assert.equal(await page.locator('.card').count(),43);
  await page.locator('#scope').selectOption('cases');
  await page.locator('#paired').click();
  assert((await page.locator('#badge').innerText()).includes('GPT-only'));
  await page.waitForFunction(()=>document.querySelector('#video').readyState>=2);
  await page.locator('#play').click();
  await page.waitForFunction(()=>document.querySelector('#video').currentTime>0.1);
  await page.locator('#play').click();
  const before=await page.locator('#video').evaluate(v=>v.currentTime);
  await page.locator('#forward').click();
  assert(Math.abs(await page.locator('#video').evaluate(v=>v.currentTime)-before-0.04)<0.002);
  await page.locator('#seek').fill('0.5');
  await page.waitForFunction(()=>!document.querySelector('#video').seeking);
  assert(Math.abs(await page.locator('#video').evaluate(v=>v.currentTime/v.duration)-0.5)<0.01);
  await page.locator('#speed').selectOption('4');
  assert.equal(await page.locator('#video').evaluate(v=>v.playbackRate),4);
  await page.setViewportSize({width:1440,height:1050});
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:path.join(root,'gallery-desktop.png')});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(root,'gallery-mobile.png')});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Gallery overflows mobile viewport');
  assert.deepEqual(errors,[]);
  const result={status:'passed',paintedBars:painted,caseCards:100,clipCards:43,desktop:true,mobile:true,videoPlayback:true,seek:true,frameStep:true,referenceHover:true,pageErrors:errors};
  fs.writeFileSync(path.join(root,'browser-smoke.json'),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
