const {chromium}=require('/tmp/rollout-review-browser.HpuzaB/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const base='http://127.0.0.1:8768/',out=path.resolve('runtime/report_fresh_qa');
fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('.rr-report').waitFor();await page.evaluate(()=>document.fonts.ready);
  await page.waitForFunction(()=>document.querySelectorAll('[data-component-id="opening-success-ranking"] .recharts-bar-rectangle').length===12);
  const body=await page.locator('body').innerText();
  assert(!/\bv[123]\b|原始标注|原标注|context 版本/.test(body),'Internal wording remains in report');
  assert(!body.includes('Ask ChatGPT')&&!body.includes('Publish')&&!body.includes('As of'),'Global toolbar remains visible');
  assert.equal(await page.locator('.dashboard-topbar').count(),0);
  const board=await page.locator('#leaderboard').boundingBox(),title=await page.locator('.rr-hero h1').boundingBox();
  assert(board.y+board.height<title.y,'Leaderboard must precede report title');
  assert.equal(await page.locator('.rr-rank-table th').count(),12);
  assert.equal(await page.locator('.rr-model-logo img').count(),13);
  assert(await page.locator('.rr-model-logo img').evaluateAll(xs=>xs.every(x=>x.complete&&x.naturalWidth>0)),'Broken model logos');
  const bars=await page.locator('[data-component-id="opening-success-ranking"] .recharts-bar-rectangle').evaluateAll(xs=>xs.map(x=>{const b=x.getBoundingClientRect();return {w:b.width,h:b.height,y:b.y+b.height};}));
  assert(bars[0].h>bars[0].w*2,'Top chart is not vertical');
  assert(Math.max(...bars.map(b=>b.y))-Math.min(...bars.map(b=>b.y))<2,'Bars do not share a zero baseline');
  await page.screenshot({path:path.join(out,'homepage.png')});
  await page.locator('#teaser').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>document.querySelector('#teaser video').currentTime>.15);
  assert.equal(await page.locator('#teaser video').evaluate(v=>v.controls),false);
  await page.locator('#teaser .rr-video-card').click();
  await page.locator('#teaser dialog[open] video').waitFor();
  assert(await page.locator('#teaser dialog[open] video').evaluate(v=>v.controls));
  await page.waitForFunction(()=>document.querySelector('#teaser dialog video')?.currentTime>.1);
  await page.locator('#teaser dialog video').evaluate(v=>{v.pause();v.currentTime=20;v.playbackRate=4;});
  await page.waitForFunction(()=>{const v=document.querySelector('#teaser dialog video');return !v.seeking&&Math.abs(v.currentTime-20)<.002;});
  assert.equal(await page.locator('#teaser dialog video').evaluate(v=>v.playbackRate),4);
  await page.screenshot({path:path.join(out,'report-video-modal.png')});
  await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);
  const ref=page.locator('#motivation a[href="https://github.com/zjwzcx/Awesome-Astra-Embodied-AI"]');
  await ref.hover();
  await page.getByText('用户推荐的社区索引，区分仿真控制、真机控制、调用预训练策略、Real-to-sim 和环境/RL 构建。作为发现原始案例的入口，不把不同演示的结果混成统一基准。',{exact:true}).waitFor({state:'visible'});
  await page.screenshot({path:path.join(out,'citation-hover.png')});
  await page.keyboard.press('Escape');
  await page.locator('#method').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'method.png')});
  await page.getByRole('button',{name:'成功率',exact:true}).click();
  await page.locator('[data-component-id="panel-sr-ranking"]').waitFor();
  await page.getByRole('button',{name:'平均 Score',exact:true}).click();
  assert.equal(await page.locator('#results .rr-table tbody tr').count(),10);
  const clip=page.locator('.rr-clip').first();await clip.scrollIntoViewIfNeeded();
  assert((await clip.locator('.rr-video-card').boundingBox()).width>=1000,'Body video too small');
  await page.screenshot({path:path.join(out,'large-body-video.png')});
  assert.equal(await page.locator('.rr-clip').count(),12);
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Report overflow');
  await page.screenshot({path:path.join(out,'homepage-mobile.png')});
  await page.setViewportSize({width:1440,height:1050});
  await page.goto(base+'gallery.html',{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('.task-button').count(),10);assert.equal(await page.locator('.rollout-button').count(),5);
  await page.waitForFunction(()=>document.getElementById('video').currentTime>.15);
  assert.equal(await page.locator('#video').evaluate(v=>v.controls),false);
  const first=await page.locator('#video').getAttribute('src');
  await page.locator('.rollout-button').nth(1).click();assert.notEqual(await page.locator('#video').getAttribute('src'),first);
  const seed=await page.locator('#facts').innerText();
  await page.locator('#paired').click();assert.equal(await page.locator('.method-tab[data-method="gpt"]').getAttribute('aria-pressed'),'true');
  assert((await page.locator('#facts').innerText()).includes(seed.match(/Seed\s+(\d+)/)[1]));
  await page.locator('[data-task="imitate_sorting_sequence"]').click();
  await page.locator('#video-card').click();await page.locator('#video-dialog[open]').waitFor();
  await page.waitForFunction(()=>document.getElementById('expanded-video').currentTime>.1);
  assert(await page.locator('#expanded-video').evaluate(v=>v.controls));
  await page.screenshot({path:path.join(out,'gallery-modal.png')});
  await page.locator('#close-dialog').click();
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:path.join(out,'gallery.png')});
  await page.locator('#scope').selectOption('clips');assert((await page.locator('.rollout-button').count())>0);
  assert(!/\bv[123]\b|原始标注|原标注|context 版本/.test(await page.locator('body').innerText()),'Internal wording remains in gallery');
  await page.locator('#search').fill('no_such_task');assert.equal(await page.locator('.task-button').count(),0);
  await page.locator('#search').fill('');assert((await page.locator('.task-button').count())>0);
  await page.locator('#scope').selectOption('cases');
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Gallery overflow');
  await page.screenshot({path:path.join(out,'gallery-mobile.png')});
  assert.deepEqual(errors,[]);
  const html=await(await page.request.get(base)).body();
  const result={status:'passed',html_sha256:crypto.createHash('sha256').update(html).digest('hex'),
   topbarRemoved:true,verticalBars:12,modelIcons:13,chartBeforeTitle:true,bodyVideoMinWidth:1000,
   bodyVideos:13,inlineAutoplay:true,nativeModalControls:true,modalSeek20s:true,modalPlaybackRate4:true,escapeClose:true,citationHover:true,metricSwitch:true,
   galleryTasks:10,rolloutsPerMethodTask:5,sameSeedSwitch:true,taskSearch:true,
   internalVersionLabelsRemoved:true,originalCommentsHidden:true,mobile:true,pageErrors:errors};
  fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
